repos:
  - repo: local
    hooks:
      - id: ruff-lint-code
        name: Lint
        entry: make lint
        language: system
        pass_filenames: false

      - id: ruff-format-code
        name: Format
        entry: make format
        language: system
        pass_filenames: false

      - id: run-tests
        name: Test
        entry: make test
        language: system
        pass_filenames: false